const {chromium}=require(process.cwd()+'/web/node_modules/@playwright/test');
const fs=require('node:fs');const path=require('node:path');const out=__dirname;
(async()=>{const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});await page.route('**/api/**',route=>{const req=route.request();if(req.method()==='GET'||/auth-with-password|auth-refresh|\/api\/kankaku\/totals/.test(req.url()))return route.continue();return route.abort();});await page.goto('http://127.0.0.1:3003/login');await page.locator('input[type=email]').fill('david@kankaku.local');await page.locator('input[type=password]').fill('kankaku-dev-owner');await page.locator('button[type=submit]').click();await page.waitForTimeout(1500);await page.goto('http://127.0.0.1:3003/entries');await page.waitForTimeout(5000);
const original=await page.locator('body').innerHTML();const reports=[];
for(const variant of ['A','B']){await page.evaluate(({original,variant})=>{
// Replace the rendered tree with an inert clone: no Vue handlers or authored requests.
document.body.innerHTML=original;document.querySelectorAll('script').forEach(e=>e.remove());
const layout=document.querySelector('[data-testid=entries-filter-layout]');const controls=document.querySelector('[data-testid=entries-filter-controls]');const fields=[...controls.children];const actions=document.querySelector('[data-testid=entries-filter-actions]');const card=layout.parentElement;
const style=document.createElement('style');style.textContent=`[data-testid=entries-filter-layout]{display:block;padding:16px} .preview-row{display:flex;align-items:end;gap:12px;flex-wrap:wrap}.preview-secondary{margin-top:16px;padding-top:16px;border-top:1px solid var(--border)} .preview-note{font-size:12px;color:var(--muted-foreground);margin-top:8px}.preview-button{height:36px;padding:0 12px;border:1px solid var(--input);border-radius:var(--radius-md);background:var(--background);font-size:14px;font-weight:500}.preview-button:focus-visible{outline:2px solid var(--ring);outline-offset:3px}.preview-button[aria-expanded=true]{background:var(--accent);color:var(--accent-foreground)} .preview-mode{display:flex;gap:2px;background:var(--muted);padding:3px;border-radius:var(--radius-md);align-self:end}.preview-mode button{border:0;background:transparent;height:30px;padding:0 12px;font-size:14px}.preview-mode button:first-child{background:var(--background);border-radius:6px;box-shadow:0 1px 2px #0001} [data-testid=entries-filter-actions]{border:0;padding:0;margin-left:auto} [data-testid=entries-filter-actions] button{width:auto!important;padding:0 12px!important;gap:8px} [data-slot=table-container]{overflow-x:auto} table th,table td{padding-left:6px!important;padding-right:6px!important} [hidden]{display:none!important}`;document.head.append(style);
layout.replaceChildren();const main=document.createElement('div');main.className='preview-row';layout.append(main);for(const i of [7,0,1])main.append(fields[i]);actions.querySelector('button').append(document.createTextNode('Exportar'));main.append(actions);
const secondary=document.createElement('div');secondary.id='preview-extra';secondary.className='preview-secondary';layout.append(secondary);
const entry=document.createElement('div');entry.className='preview-row';for(const i of [5,4,8])entry.append(fields[i]);secondary.append(entry);const note=document.createElement('p');note.className='preview-note';note.textContent='Modelo, calidad y búsqueda están disponibles solo en Entradas; no se aplican a las sesiones agrupadas.';secondary.append(note);const aux=document.createElement('div');aux.className='preview-row';aux.style.marginTop='16px';for(const i of [3,2,6])aux.append(fields[i]);secondary.append(aux);
if(variant==='B'){const mode=document.createElement('div');mode.className='preview-mode';mode.innerHTML='<button type="button" aria-pressed="true">Sesiones</button><button type="button" aria-pressed="false">Entradas</button>';main.insertBefore(mode,actions);const button=document.createElement('button');button.id='preview-more';button.className='preview-button';button.type='button';button.textContent='Más filtros · 0';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','preview-extra');main.insertBefore(button,actions);secondary.hidden=true;button.onclick=()=>{secondary.hidden=!secondary.hidden;button.setAttribute('aria-expanded',String(!secondary.hidden));};const grouping=card.nextElementSibling;if(grouping?.querySelector('[role=switch]'))grouping.remove();}
},{original,variant});
for(const theme of ['light','dark']){await page.evaluate(theme=>{document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.style.colorScheme=theme;},theme);await page.waitForTimeout(500);for(const expanded of variant==='B'?[false,true]:[false]){if(variant==='B'){await page.evaluate(expanded=>{const panel=document.querySelector('#preview-extra');panel.hidden=!expanded;document.querySelector('#preview-more').setAttribute('aria-expanded',String(expanded));},expanded);await page.locator('#preview-more').focus();await page.keyboard.press('Enter');const toggled=await page.locator('#preview-more').getAttribute('aria-expanded');if(toggled!==String(!expanded))throw Error('Keyboard toggle failed');await page.keyboard.press('Enter');await page.locator('#preview-more').evaluate(e=>e.blur());}
const name=`${variant}${expanded?'-expanded':''}-${theme}`;const evidence=await page.evaluate(()=>{const table=document.querySelector('table');const card=table.closest('[data-slot=card]');const content=table.closest('[data-slot=card-content]');const rect=table.getBoundingClientRect();const last=table.querySelector('tbody tr td:last-child')?.getBoundingClientRect();const panel=document.querySelector('[data-testid=entries-filter-layout]').getBoundingClientRect();return {documentOverflow:document.documentElement.scrollWidth>innerWidth,filterPanel:{top:panel.top,bottom:panel.bottom},table:{top:rect.top,left:rect.left,right:rect.right},expanderFullyVisible:!!last&&last.right<=innerWidth&&last.left>=rect.left,cardPadding:card&&getComputedStyle(card).padding,contentPadding:content&&getComputedStyle(content).padding,filterDimensions:document.querySelectorAll('[data-testid=entries-filter-layout] label').length,rows:table.querySelectorAll('tbody tr').length,font:getComputedStyle(document.body).fontFamily};});reports.push({name,viewport:'1440x1000',...evidence});await page.screenshot({path:path.join(out,name+'.png')});}}
fs.writeFileSync(path.join(out,variant+'.html'),await page.content());}
fs.writeFileSync(path.join(out,'measurements.json'),JSON.stringify(reports,null,2));for(const report of reports){const f=path.join(out,report.name+'.png');if(fs.statSync(f).size<10000)throw Error('Empty image');}console.log(JSON.stringify(reports,null,2));await browser.close();})().catch(e=>{console.error(e);process.exitCode=1;});